version: "3"

# Computing components of an application;
# abstract concept implemented on platforms by running the same container image (and configuration) one or more times
services:
  postgres:
    image: "postgres:13"
    container_name: "postgres_for_etl"
    environment:  # used to pass environment variables straightly
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # mounted at /var/lib/postgresql/data - the directory where
#       Postgres stores all the relevant tables and databases, postgres-db-volume defined at the last line of the file

  webserver:
    build: .
    command: webserver
    depends_on:
      - postgres
    volumes:
      - ./data/airflow/dags:/usr/local/airflow/dags
      - ./data/airflow/logs:/usr/local/airflow/logs
    ports:
      - "8080:8080"

volumes:
  data:
