version: "3"

# Computing components of an application;
# abstract concept implemented on platforms by running the same container image (and configuration) one or more times
services:
  postgres:
    image: "postgres:13"
    container_name: "postgres_for_etl"
    environment: # used to pass environment variables straightly
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      # mounted at /var/lib/postgresql/data - the directory where Postgres stores all the relevant tables and databases,
      # postgres-db-volume defined at the last line of the file
      - ./data/postgres:/var/lib/postgresql/data

  webserver:
    build: .
    command: webserver
    depends_on:
      - postgres
    volumes:
      - ./dags:/SoftServe-Internship_ETL-project/airflow/data/dags
      - ./data/logs:/SoftServe-Internship_ETL-project/airflow/data/logs
    ports:
      - "8080:8080"

volumes:
  data:
  dags:
