version: "3"


services:
  postgres:
    image: "postgres:13"
    container_name: "postgres_for_etl"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  webserver:
    build: .
    command: webserver
    depends_on:
      - postgres
    volumes:
      - ./dags:/SoftServe-Internship_ETL-project/dags
      - ./data/logs:/SoftServe-Internship_ETL-project/logs
    ports:
      - "8080:8080"


volumes:
  data:
  dags:
